// Every calculation the platform makes, in one place, so a risk manager or auditor can check the
// method without reading the code. Plain data: the Methodology page renders it, and the test
// checks that every section names the module the numbers come from.
//
// Each item: { en, sv } for the name, `formula` (plain text / Unicode maths, not translated),
// { en, sv } notes, and optionally `params` — the settings or fields the calculation reads.
export const METHODOLOGY = [
  {
    id: 'valuation', module: 'instruments.js · pricing.js',
    title: { en: 'Valuation per instrument' },
    intro: { en: 'Every position returns market value (MV), gross exposure, signed net exposure and its sensitivities in the base currency. Amounts in other currencies are converted at the FX table (ECB reference rates or your own).' },
    items: [
      { en: 'Equity, ETF, fund, commodity (ETC), alternative', formula: 'MV = quantity × price × FX', notes: { en: 'Exposure = |MV|. Equity delta = MV. Funds and ETFs: the look-through class decides whether the MV counts as equity delta, duration (via the duration field) or commodity delta; a mixed fund uses the equity share.' } },
      { en: 'Fixed-coupon bonds (government, corporate)', formula: 'Dirty = Σ CF_i · (1 + y/f)^(−n_i)   with n_i = i + w,  w = days to next coupon / days in period\nMV = nominal × dirty / 100 × FX;  accrued = coupon/f × (1 − w)', notes: { en: 'Street convention on a coupon schedule rolled back from maturity (unadjusted). From a clean price the yield is solved with Newton–Raphson (bisection fallback); from a yield the price follows. A zero coupon is the same formula with no coupons.' }, params: 'price (clean %), yield %, coupon %, freq, maturity' },
      { en: 'Duration and convexity', formula: 'Macaulay D = Σ t_i · PV_i / P;   modified D = D / (1 + y/f)\nConvexity = Σ CF_i · disc_i · n_i(n_i+1) / (f² · P · (1+y/f)²)', notes: { en: 'Per-100 figures, then applied to MV. DV01 per position = −MV × modified duration × 1e−4.' } },
      { en: 'Floating rate notes', formula: 'rate duration = min(years to maturity, 1/f);  spread duration = modified duration at the current coupon', notes: { en: 'Valued as a bond at the current coupon. The rate duration only runs to the next reset; the credit (spread) duration runs to maturity.' } },
      { en: 'Money market / T-bills', formula: 'zero-coupon bond formula with coupon = 0', notes: { en: 'Government if the issuer name says so (state, treasury, Riksgälden…); otherwise it carries spread duration and counts against the issuer limit.' } },
      { en: 'Cash / deposits', formula: 'MV = amount × FX', notes: { en: 'Negative for overdrafts or unsettled payables.' } },
      { en: 'Futures', formula: 'notional = contracts × price × multiplier × FX;  MV = unsettled variation margin\nexposure = |notional|;  net = notional (signed)', notes: { en: 'Daily margined, so the market value is only the unsettled variation margin (the MTM field); a file value above a quarter of the notional is taken to be the notional, ignored and flagged. Equity: delta = notional, beta from the field. Bond futures: DV01 = −notional × CTD duration × 1e−4. Commodity: commodity delta = notional. FX futures: long the traded currency, short the quote currency. A reported notional replaces the model notional when present and the setting is on.' } },
      { en: 'Options (Black-Scholes-Merton / Black-76 / Garman-Kohlhagen)', formula: 'd1 = [ln(S/K) + (r − q + σ²/2)T] / (σ√T),  d2 = d1 − σ√T\nCall = S e^(−qT) N(d1) − K e^(−rT) N(d2);  Put = K e^(−rT) N(−d2) − S e^(−qT) N(−d1)\nΔ_call = e^(−qT) N(d1);  Γ = e^(−qT) φ(d1) / (S σ √T);  vega = S e^(−qT) φ(d1) √T / 100 (per vol point);  θ per day', notes: { en: 'q = dividend yield for equities, the foreign rate for FX (Garman-Kohlhagen), and q = r for rates and commodities (Black-76 on a forward). MV = the market value in your file if given, else contracts × multiplier × premium, else the model price (flagged). An option with a counterparty in Issuer is OTC and counts toward the OTC counterparty limit. Delta-adjusted exposure = contracts × multiplier × Δ × S × FX; that is what exposure, net, equity delta and the commitment use. Cash gamma = units × Γ × S². Reported delta (0.45 or 45 %) or reported delta-adjusted exposure overrides the model when present: magnitudes from the file, signs from long/short and call/put. Flagged when the implied delta differs from the model by more than 0.05 or the notional by more than 10 %.' }, params: 'strike, maturity, underlyingPrice, vol %, rate %, divYield %, multiplier, reportedDelta, reportedNotional, reportedDeltaExposure' },
      { en: 'FX forwards / swaps', formula: 'MV = buy amount × FX_buy − sell amount × FX_sell  (or the entered market value)\nexposure = max(|buy|, |sell|);  net = 0', notes: { en: 'Without the counterparty\'s MTM, spot valuation: forward points and discounting are ignored, which is material for long-dated hedges between currencies with different rates, so the position is flagged. Give the MTM. The two legs feed the currency table as a hedge.' } },
      { en: 'Interest rate swaps', formula: 'A = Σ (1/f) · (1 + s/f)^(−n_i)   (annuity at the current par rate s)\nMV ≈ ±N × (fixed − s) × A   (+ receive fixed, − pay fixed)\nDV01 = ∓N × A × 1e−4', notes: { en: 'Single flat curve at the entered par rate; an entered market value overrides the estimate. Receive fixed adds duration, pay fixed removes it. Notional counts as fixed-income exposure with the same sign.' } },
      { en: 'Credit default swaps', formula: 'A = risky annuity at (2.5 % + market spread), quarterly\nMV ≈ ±N × (market spread − contract spread) × 1e−4 × A   (+ bought protection)\nCS01 = ±N × A × 1e−4;  net exposure = −N for bought, +N for sold protection', notes: { en: 'Selling protection is long credit (like owning the bond without funding it) and counts toward the issuer limit; buying protection gains when spreads widen.' } }
    ]
  },
  {
    id: 'instruments2', module: 'instruments.js · pricing.js',
    title: { en: 'Instruments beyond the plain ones' },
    intro: { en: 'How the less common instruments are valued and which models are used. The counterparty’s MTM, where given, always wins over the model value; the model then only supplies the risk.' },
    items: [
      { en: "Inflation-linked bonds", formula: "MV = nominal × (real clean price + real accrued) / 100 × index ratio × FX", notes: { en: "Index ratio = reference CPI ÷ base CPI from your file; without it 1.00 is used and flagged. Duration is to real yields. The same duration also gives breakeven inflation sensitivity (inflation factor): nominal yield = real yield + breakeven, so a linker gains when breakeven widens at an unchanged nominal yield." }, params: "price or yield (real), indexRatio, coupon, maturity" },
      { en: "Callable and perpetual bonds (AT1, Tier 2)", formula: "yield to worst: priced to maturity and to the next call date (redeemed at the call price); the lower yield sets price, duration and convexity", notes: { en: "A perpetual needs a future call date; after the last call it cannot be priced and is flagged. Only the next call is considered." }, params: "callDate, callPrice" },
      { en: "Dirty prices", formula: "clean = dirty − accrued (from the coupon schedule); then as a clean price", notes: { en: "For files that quote prices including accrued interest; the Dirty price column is recognised automatically." }, params: "dirtyPrice" },
      { en: "Convertible bonds", formula: "MV at market price;  equity delta = MV × δ;  rate and spread sensitivity × (1 − δ)", notes: { en: "δ is the reported equity delta (0–1 or %); 0.5 is assumed and flagged without it. The option is not modelled." }, params: "reportedDelta" },
      { en: "Certificates and structured products", formula: "MV = quantity × price × FX;  exposure = MV × leverage (negative = bear/short)", notes: { en: "Leverage from the column, else from names such as “BULL OMX X5 AVA”, else 1 and flagged. The issuer counts toward the issuer limits (credit risk). Mini futures and turbos: exposure = quantity × ratio × underlying, zero (and flagged) once the stop-loss barrier is hit; model value = (underlying − financing level) × ratio. Autocalls and other payoffs without a model: market price, and the issuer's delta entered as leverage. Capital protected: zero-coupon floor + participation × call." }, params: "certType, leverage, strike (financing level), barrier, autocallLevel, protectionLevel, coupon, vol" },
      { en: "Equity swaps, CFDs, total return swaps", formula: "notional = quantity × underlying price × FX (exposure, equity delta);  MV = MTM from the file, else quantity × (price − cost)", notes: { en: "The market value is the unrealised result, never the notional. Counterparty in Issuer counts toward the OTC counterparty limit." }, params: "underlyingPrice or price, mtm, costPrice" },
      { en: "Cross-currency swaps", formula: "MV = counterparty MTM (else final exchange at spot, flagged);  FX exposure = both legs;  with a fixed rate, IR01 per leg = ∓ notional × annuity × 1e−4", notes: { en: "Floating legs are treated as having no rate duration." }, params: "buy/sell leg, fixedRate, mtm" },
      { en: "Repos and term deposits", formula: "MV = cash amount × FX;  days to liquidate = days to maturity (open repo: 1)", notes: { en: "Reverse repo (cash lent) positive, repo (cash borrowed) negative. Counterparty exposure = cash lent − collateral × (1 − haircut); in a repo, collateral posted beyond the cash received. Without a collateral value the full amount counts and is flagged." }, params: "maturity, rate, collateralValue, haircut" },
      { en: "Securities lending", formula: "MV = 0 (the lent securities stay in the holdings);  counterparty exposure = value lent − collateral × (1 − haircut)", notes: { en: "Off balance sheet: it adds no market risk, only counterparty risk, which counts toward the OTC counterparty limit per borrower." }, params: "qty (value lent), collateralValue, haircut, issuer (borrower)" },
      { en: "Swaptions and caps/floors", formula: "Bachelier (normal vol, bp):  PV = A · [ω(F − K)N(ωd) + σ√T n(d)],  d = (F − K)/(σ√T)\nBlack (lognormal %) otherwise;  A = annuity of the underlying swap;  caps/floors = sum of caplets, first period left out", notes: { en: "IR01 = ∂PV/∂F × 1e−4, vega per bp (normal) or per vol point. Stress revalues the option at the shocked forward and vol, so the convexity is in the stress P&L. Rate vega is shown per position but is not a VaR factor (the volatility factor is equity implied vol)." }, params: "payerReceiver/capFloor, strike, maturity, tenor, marketRate (forward), vol, volType, freq" },
      { en: "Zero-coupon inflation swaps", formula: "PV = ±N · e^(−rT) · [(1 + b)^T − (1 + k)^T]  (b = market breakeven, k = contract fixed rate)", notes: { en: "Risk goes on a breakeven inflation factor per currency (vol in the market assumptions, correlated with rates and commodities) plus a small nominal-rate IR01 from discounting." }, params: "direction, fixedRate, breakeven, marketRate, maturity" },
      { en: "Barrier and digital options", formula: "barriers: Reiner-Rubinstein closed form (continuous monitoring), in + out = vanilla\ndigitals: cash-or-nothing, PV = payout · e^(−rT) · N(ωd₂)\ndelta, gamma, vega by revaluation at ±1 % and ±1 vol point", notes: { en: "A breached barrier is flagged: knock-out is worth zero, knock-in becomes the vanilla. Discrete monitoring is not adjusted for. Stress revalues the option at the shocked spot and vol." }, params: "exoticKind, optType, barrierType, barrier, payout, strike, underlyingPrice, vol" },
      { en: "ABS, MBS, CLO and amortising bonds", formula: "cash flows = scheduled amortisation + prepayments at CPR (SMM = 1 − (1 − CPR)^(1/f));  outstanding = nominal × pool factor\nWAL = Σ t · principal_t / Σ principal_t;  yield, duration and convexity from those cash flows", notes: { en: "Without CPR only the scheduled amortisation is used, and this is flagged. CLO tranches that do not amortise before the reinvestment period ends can be entered as bullets with the expected call date." }, params: "structure = amortising, cpr, poolFactor" },
      { en: "Other OTC derivatives (MTM only)", formula: "MV = counterparty MTM;  exposure = |notional|;  net = notional × δ;  IR01 = −net × duration × 1e−4;  volatility: vega = vega notional", notes: { en: "Asian, lookback, cliquet, basket, rainbow and quanto options, variance, volatility, correlation and commodity swaps: the path- or correlation-dependent payoffs where a model on this site would be worse than the counterparty valuation. The risk is only as good as the delta, duration or vega supplied. The same MTM-only treatment, flagged, applies to a swaption, cap, inflation swap or barrier option whose file lacks the pricing inputs." }, params: "mtm, reportedDelta, duration, vega" },
      { en: "STIR futures (Euribor, €STR, SOFR, SONIA)", formula: "price = 100 − rate;  DV01 = contracts × multiplier × 0.01;  notional = DV01 / (0.25 × 1e−4)", notes: { en: "Recognised when the underlying is rates, duration ≤ 0.5 and the price is between 80 and 110." }, params: "multiplier, duration" },
      { en: "Volatility futures and options (VIX, VSTOXX)", formula: "vega per vol point = contracts × multiplier × FX (options: × delta)", notes: { en: "One index point is one vol point; long volatility gains in the stress scenarios where implied vol rises." }, params: "underlyingClass = volatility" },
      { en: "American and futures-style options", formula: "American: Cox-Ross-Rubinstein tree, 200 steps;  futures-style: MV = unsettled margin only", notes: { en: "Greeks stay Black-Scholes. A warrant or option with only a market price is valid; its exposure is then the market value and it is flagged." }, params: "exercise, margining" },
      { en: "Prices in minor units and unknown types", formula: "GBp/GBX, ZAc, ILA = 1/100 of GBP, ZAR, ILS", notes: { en: "A type code the platform does not recognise is not guessed: the row is kept but not valued until it is mapped." }, params: "ccy, type" }
    ]
  },
  {
    id: 'exposure', module: 'analytics.js · allocation.js',
    title: { en: 'Exposure and asset allocation' },
    items: [
      { en: 'NAV, gross and net exposure', formula: 'NAV = Σ MV;  gross = Σ exposure / NAV;  net = Σ net exposure / NAV\ncommitment = Σ exposure of derivatives / NAV', notes: { en: 'Commitment approach: futures and swaps at notional, options delta-adjusted, FX forwards at the larger leg. No netting of hedges, so it is conservative against the UCITS 100 % limit.' } },
      { en: 'Allocation at market value', formula: 'weight_class = Σ MV in class / NAV', notes: { en: 'Sector excludes cash, FX forwards, swaps and government bonds; region uses the country code; issuer uses the issuer field (name if empty).' } },
      { en: 'Economic exposure per asset class', formula: 'economic = physical MV + derivative overlay\noverlay = Σ (net exposure − MV) of derivatives on the class', notes: { en: 'Futures and swaps at signed notional, options at delta-adjusted exposure, sold CDS = long credit. Mixed funds are split by equity share. FX forwards and FX options are currency hedges, not asset-class bets, so only their MTM counts here. Interest-rate derivatives are at notional, not duration-weighted.' } },
      { en: 'Mandate check', formula: 'status = breach if economic weight < min or > max;  warning within 2 percentage points of a limit;  active = economic − target', notes: { en: 'Targets and ranges are entered per class in % of NAV.' } },
      { en: 'Concentration', formula: 'HHI = Σ w_i²  over non-cash, non-derivative holdings;  effective N = 1 / HHI;  top 10 = Σ of the ten largest weights', notes: { en: '' } },
      { en: 'Currency exposure', formula: 'gross_ccy = Σ MV of holdings in ccy (options at MV, futures at margin)\nhedge_ccy = Σ legs of FX forwards, FX futures and FX options in ccy\nnet = gross + hedge;  hedge ratio = −hedge / gross', notes: { en: 'Everything in base-currency terms; the base currency itself is not shown.' } }
    ]
  },
  {
    id: 'fixedIncome', module: 'analytics.js',
    title: { en: 'Fixed income' },
    items: [
      { en: 'Portfolio figures', formula: 'YTM, modified duration, spread duration, convexity = MV-weighted averages over bonds, FRNs and money market\nportfolio duration = −Σ DV01 / NAV / 1e−4  (derivatives and funds included)\nportfolio spread duration = −Σ CS01 / NAV / 1e−4', notes: { en: 'The weighted averages describe the bond book; the portfolio durations describe the whole fund and therefore include swaps, bond futures, CDS and bond funds.' } },
      { en: 'Maturity and DV01 ladders', formula: 'buckets 0–1, 1–3, 3–5, 5–7, 7–10, 10+ years by years to maturity', notes: { en: 'The MV ladder covers bonds only; the DV01 ladder also places swaps and futures, so a receiver swap or a short bond future shows up.' } },
      { en: 'Average rating', formula: 'score AAA=1 … D=22; average = MV-weighted score, mapped back to the nearest notch\nhigh yield = rating below BBB−', notes: { en: 'Linear average of notches, which is the common simplification (agencies use non-linear scales).' } }
    ]
  },
  {
    id: 'risk', module: 'analytics.js (factorModel, historicalRisk) · riskstats.js',
    title: { en: 'Risk: VaR, expected shortfall, volatility' },
    items: [
      { en: 'Parametric (factor) model', formula: 'factors: equity per region (Nordics, Europe, North America, Asia-Pacific, emerging, global), credit IG and HY (bp), commodity, volatility (vol points), rates per currency (bp), FX per currency\ns_k = Σ_i sensitivity_i,k   (equity: delta × beta; rates: DV01; credit: CS01; FX: amount; vol: vega; commodity: delta)\nσ² = sᵀ Σ s + Σ_i (specific vol × |equity delta_i|)²,   Σ_kl = ρ_kl σ_k σ_l\nVaR = z_c · σ · √(h/252);  ES = σ · √(h/252) · φ(z_c) / (1 − c)', notes: { en: 'Delta-normal: linear in the factors, gamma ignored. Vols and correlations are the capital-market assumptions in Settings. Each equity position loads on the factor of its country\'s region (no country: global); the regional factors correlate at ρ(region, region), emerging markets with their own vol. Credit sensitivity goes to the IG or HY factor by rating; unrated credit counts as HY except money market paper. Contributions per factor group and per position are Euler contributions s_k (Σ s)_k / σ, so they add up to the total. The asset-class view sums the same contributions per position class: equity = equity market + stock-specific + implied vol of equity options + equity derivatives; fixed income = rates + credit + rate/credit derivatives; currency = the FX factors of every position (holdings and hedges together).' }, params: 'confidence, horizonDays, CMA vols and correlations, equitySpecificVol, beta' },
      { en: 'Historical simulation', formula: 'P&L_t = Σ_i exposure_i × [(1 + r_i,t)(1 + fx_i,t) − 1]   (futures/options at delta-adjusted exposure, others at MV)\nVaR = −quantile_(1−c)(P&L) · √h;  ES = −mean(P&L ≤ quantile) · √h;  vol = stdev(P&L) · √252 / NAV', notes: { en: 'Back-cast: today\'s positions on the price history you upload (matched by ISIN, ticker or name; FX series as CCY+BASE). Coverage = covered exposure / risky NAV. Positions without a series are listed as uncovered. Used as the headline when coverage ≥ 70 % and ≥ 120 observations (or when chosen in Settings).' } },
      { en: 'EWMA VaR', formula: 'σ²_t = λ σ²_(t−1) + (1 − λ) P&L_t²,  λ = 0.94 (half-life ≈ 11 days), seeded with the mean square of the first 20 days\nVaR = z_c · σ_T · √h;  ES = σ_T · √h · φ(z_c) / (1 − c)\ncontribution_i = EWMA cov(P&L_i, P&L) / σ_T · √252', notes: { en: 'RiskMetrics on the same back-cast as historical simulation. Reacts to the current market; the ratio to the long-run volatility is shown with it. Normal quantile, so fat tails are not in it — compare with the historical figure.' }, params: 'confidence, horizonDays' },
      { en: 'Statistical risk drivers (PCA)', formula: 'z_i,t = (P&L_i,t − mean_i) / sd_i  for the up to 60 largest covered positions with ≥ 60 common days\nR = Ledoit-Wolf shrinkage of corr(z) towards I:  R = δ I + (1 − δ) S,  δ = min(β², d²) / d²\nΣ = D R D (D = diag(sd));  Σ = Σ_k λ_k v_k v_kᵀ  (Jacobi)\nshare_k = λ_k (v_k · 1)² / Σ_j λ_j (v_j · 1)²;  effective bets = exp(−Σ share_k ln share_k)', notes: { en: 'A factor model estimated from the data instead of assumed: how many independent things really drive the portfolio\'s variance, and which holdings load on each. Shrinkage keeps a short history with many holdings from producing spurious structure. Descriptive only — it does not feed the VaR.' } },
      { en: 'Correlation matrix and rolling volatility', formula: 'Pearson correlation of daily returns for the 12 largest covered positions;  rolling vol = stdev over 63 trading days · √252', notes: { en: '' } }
    ]
  },
  {
    id: 'performance', module: 'analytics.js (perfStats)',
    title: { en: 'Performance statistics' },
    items: [
      { en: 'Return and risk', formula: 'total = Π(1 + r_t) − 1;  CAGR = (1 + total)^(252/n) − 1;  vol = stdev(r) · √252\nSharpe = (CAGR − rf) / vol;  Sortino = (CAGR − rf) / downside,  downside = √(Σ min(0, r_t − rf/252)² / n) · √252\nmax drawdown = min(NAV_t / peak_t − 1);  Calmar = CAGR / |max DD|', notes: { en: 'Daily returns are the back-cast portfolio return (P&L / NAV). VaR 95/99 and ES are empirical quantiles of the daily returns. Skew and excess kurtosis are population moments.' }, params: 'riskFree %' },
      { en: 'Against the benchmark', formula: 'β = cov(r, b) / var(b);  α = (CAGR − rf) − β (CAGR_b − rf)\ntracking error = stdev(r − b) · √252;  information ratio = (CAGR − CAGR_b) / TE\nup/down capture = mean(r | b > 0) / mean(b | b > 0), likewise for b < 0', notes: { en: 'The benchmark is a price series in the history named in Settings.' } },
      { en: 'Monthly table', formula: 'month = Π(1 + r_t) − 1 over the month;  YTD = Π(1 + month) − 1', notes: { en: '' } }
    ]
  },
  {
    id: 'stress', module: 'analytics.js (runStress) · instruments.js (stressPnl)',
    title: { en: 'Stress tests' },
    items: [
      { en: 'Scenario shocks', formula: 'each scenario = { equity %, rates bp, credit spread bp, all foreign currencies %, commodities %, volatility points }', notes: { en: 'Stylised calibrations of well-known episodes (2008, 2011, 2020, 2022) plus single-factor shocks; not replays of history.' } },
      { en: 'P&L per position', formula: 'P&L = Δ_eq · β · eq + Δ_cmd · cmd + vega · vol + ½ Γ eq² + Σ DV01_ccy · rates + CS01 · cs + ½ MV · convexity · dy²\nthen translation: P&L × fx_move + Σ currency exposure × fx_move', notes: { en: 'Options are fully repriced instead (BSM at the shocked underlying, rate and vol; rate and credit options move the underlying by −duration × shock). The cross term converts the local P&L at the shocked FX rate.' } }
    ]
  },
  {
    id: 'liquidity', module: 'analytics.js (liquidity) · insights.js (liquidityStress)',
    title: { en: 'Liquidity' },
    items: [
      { en: 'Days to liquidate', formula: 'days = ⌈ |quantity| / (ADV × participation) ⌉   when ADV is given\notherwise the instrument\'s liquidity field, else a default per type (equity 2, ETF 1, bonds 3, alternatives 180 …)', notes: { en: 'Stressed profile: half the participation rate and 1.5 × the type-based days.' }, params: 'participation %, adv, liquidityDays' },
      { en: 'Liquidity profile', formula: 'liquid within h days = Σ MV_i × min(1, h / days_i)', notes: { en: 'Pro-rata: a position that needs 10 days is 70 % sold by day 7. Illiquid = more than 90 days.' } },
      { en: 'Liquidity stress test (ESMA)', formula: 'sellable(h) = Σ MV_i · min(1, h / days_i)\ncoverage = sellable(h) / (R × NAV)   — met when ≥ 1\nwaterfall: sell in order of days_i until R × NAV;   vertical: every asset × (1 − R)', notes: { en: 'Follows ESMA\'s Guidelines on liquidity stress testing in UCITS and AIFs (redemption shock, coverage ratio, effect on the remaining investors). Derivatives are not sold, so commitment rises as NAV falls; limits are re-checked on the portfolio left behind. Market impact of the sales is not modelled.' }, params: 'redemption shock, horizon, normal/stressed' }
    ]
  },
  {
    id: 'compliance', module: 'analytics.js (compliance)',
    title: { en: 'Investment rules' },
    items: [
      { en: 'Issuer limits (UCITS-style)', formula: 'issuer exposure = Σ MV of equities, corporate bonds, FRNs, non-government money market, alternatives, commodities + notional of sold CDS\nmax issuer ≤ 10 %;  Σ issuers above 5 % ≤ 40 %;  government issuer ≤ 35 %;  bank deposits ≤ 20 %;  single fund ≤ 20 %', notes: { en: 'Status: breach above the limit, warning above 90 % of it (below 110 % for minimum rules). Group-of-issuer aggregation, look-through and collateral netting are not applied. A CDS on an index (iTraxx, CDX) is left out of the issuer limits, as UCITS art. 51(3) allows for derivatives on financial indices.' }, params: 'limits (on/off and value per rule)' },
      { en: 'Other rules', formula: 'commitment ≤ 100 %;  OTC counterparty (positive MTM of forwards, swaps, CDS) ≤ 10 %;  optional: single position, sector, high yield, 7-day liquidity ≥, cash ≥, illiquid ≤', notes: { en: '' } }
    ]
  },
  {
    id: 'oversight', module: 'insights.js · snapshots.js',
    title: { en: 'Changes, track record and limit history' },
    intro: { en: 'Built on the holdings on each date: the dates in a connected file, or snapshots you save. Every date is valued with today\'s FX table and settings.' },
    items: [
      { en: 'Holdings-based return', formula: 'r(A→B) = V(holdings_A at prices_B) / V(holdings_A at prices_A) − 1\ntrack record = Π (1 + r_t) − 1  over consecutive snapshots', notes: { en: 'What the holdings on the first date earned, so subscriptions, redemptions and intra-period trades do not distort it. Futures add their variation margin and bonds the coupons paid in the period, both of which settle into cash. A holding sold before date B is priced from the price history (last price on or before B) or, failing that, at its old price and flagged. Returns for spans under a year are not annualised (GIPS).' }, params: 'snapshots, price history, FX table' },
      { en: 'Price and trading effect, flows, turnover', formula: 'price effect_i = MV_i(A holdings, B prices) − MV_i(A)\ntrade effect_i = MV_i(B) − MV_i(A holdings, B prices)\nnet flows ≈ NAV_B − V(holdings_A at prices_B)\nturnover = min(Σ buys, Σ sells) / average NAV   (cash and derivatives excluded)', notes: { en: 'Trades between securities and cash cancel in the flow estimate, so what remains is money in or out, fees and distributions paid. Contribution per holding = price effect / NAV_A; summed arithmetically over periods.' } },
      { en: 'Active vs passive limit breaches', formula: 'for each date t:  check(holdings_t)  and  check(holdings_{t−1} at prices_t)\nbreach starts at t:  passive if the second check also breaches, else active', notes: { en: 'Passive: the unchanged portfolio would have breached anyway (market moves, or flows). Active: the trades did it. UCITS art. 57(2): a passive breach is remedied as a priority objective, taking due account of unitholders\' interests; an active breach at once. Today\'s limits are applied to every date.' } }
    ]
  },
  {
    id: 'pretrade', module: 'insights.js (whatIf, applyTrades)',
    title: { en: 'Pre-trade what-if' },
    items: [
      { en: 'Applying trades', formula: 'target weight w:  q_new = w × NAV / (MV / q)\nchange Δq:  q_new = q + Δq;   new quantity:  q_new = value\ncash_new = cash − Σ ΔMV / FX_cash', notes: { en: 'All size fields scale together (quantity, legs, MTM, reported figures). Trades are at current prices without costs or market impact; the before/after figures use the parametric model so they are comparable.' }, params: 'holdings, cash account' }
    ]
  },
  {
    id: 'attribution', module: 'insights.js (brinson, portfolioSegments)',
    title: { en: 'Performance attribution' },
    items: [
      { en: 'Brinson-Fachler', formula: 'allocation_i  = (wp_i − wb_i) · (Rb_i − Rb)\nselection_i   = wb_i · (Rp_i − Rb_i)\ninteraction_i = (wp_i − wb_i) · (Rp_i − Rb_i)\nΣ_i (allocation + selection + interaction) = Rp − Rb', notes: { en: 'Single period, market-value weights at the start. Portfolio side from two snapshots (holdings-based) or, without snapshots, today\'s holdings over the price history. A segment only the portfolio holds takes Rb_i = Rb (its effect is interaction); one only the benchmark holds takes Rp_i = Rb_i (its effect is allocation). Segments under 0.1 % of NAV go to a residual so totals reconcile.' }, params: 'benchmark weight and return per segment' }
    ]
  },
  {
    id: 'pnl', module: 'pnl.js',
    title: { en: 'Cost basis and P&L' },
    items: [
      { en: 'Average cost (transaction log)', formula: 'buy:  avg ← (q · avg + Δq · (price·unit + fees/Δq)) / (q + Δq)\nsell: realised = Δq · (price·unit − avg) − fees;  q ← q − Δq  (avg unchanged)\nselling through zero opens a short at the trade price; covering a short realises (avg − price)', notes: { en: 'Average-cost method (the Swedish tax standard, "genomsnittsmetoden"); FIFO is not offered. unit = 1 for shares and fund units, multiplier for options, 1/100 for bonds and bills (price in % of par). Quantities are signed so short positions work symmetrically. The book quantity is compared with the position; a difference is flagged, not corrected.' }, params: 'transactions: date, side, qty, price, fees, fx' },
      { en: 'Cost price without transactions', formula: 'cost basis = quantity × costPrice × unit × FX_today', notes: { en: 'For holdings loaded from a custodian file. With today\'s FX there is no FX effect to show.' }, params: 'costPrice' },
      { en: 'Unrealised P&L and FX effect', formula: 'unrealised = MV − cost basis (base ccy)\nlocal part = (price·unit − avg) × q × FX_today;  FX effect = unrealised − local part', notes: { en: 'The FX effect only appears when transactions carry the FX rate of the trade day (cost basis in base currency = Σ q · price · FX_trade). Bond MV is dirty, cost is clean, so accrued interest sits in the unrealised figure. Futures, swaps and forwards are outside the cost basis (no purchase price); their MTM is in the holdings.' } },
      { en: 'Realised P&L per period', formula: 'Σ realised of sells with trade date ≥ period start (YTD, 12 months, all)', notes: { en: 'In base currency at the trade-day FX when recorded, else today\'s.' } }
    ]
  },
  {
    id: 'fund', module: 'fund.js',
    title: { en: 'Fund calculations' },
    items: [
      { en: 'Cash-flow calendar', formula: 'coupon = nominal × coupon % / f on each schedule date;  redemption = nominal at maturity\nswap = ±N × (fixed − par) / f per period (estimate);  CDS premium = ±N × spread / 4 on IMM dates (20 Mar/Jun/Sep/Dec)\nFX forward = both legs at maturity;  option/future expiry = informational (intrinsic value / notional), not cash', notes: { en: 'Projected cash = cash today + cumulative net cash events per month.' } },
      { en: 'Indicative NAV per unit', formula: 'net assets = Σ MV − liabilities + receivables\nclass share = units × last NAV × FX / Σ over classes;  accrued fee = fee % × class assets × days / 365\nNAV per unit = (class assets − accrued fee) / FX_class / units', notes: { en: 'Fees accrue linearly on actual/365 from the entered start date. The flow simulator adds or removes base-currency cash and re-runs liquidity and the investment rules; it does not decide which assets to sell.' } }
    ]
  },
  {
    id: 'market', module: 'marketdata.js · marketsync.js',
    title: { en: 'Market data and discount curves' },
    intro: { en: 'ECB, Riksbank, US Treasury and Norges Bank data (and any source the organisation adds in market-sources.json) fetched by a scheduled GitHub Action every business day and published with the site as data/market.json. The browser downloads that one file — the site\'s, or one the organisation publishes itself (Settings) — and sends nothing.' },
    items: [
      { en: 'FX rates by valuation date', formula: 'rates = ECB euro reference rates of the latest business day ≤ valuation date (last 90 days kept)', notes: { en: 'Applied only to portfolios on the placeholder or published rates; rates typed in or imported from your own ECB file are never replaced. Outside the 90 days nothing changes. Earlier snapshot dates (Changes, track record, limit history) are valued with their own day\'s rates and curve, so holdings-based returns include the currency effect.' }, params: 'Settings → FX rates' },
      { en: 'EUR discount curve', formula: 'points: €STR (overnight) and the ECB euro area AAA government spot curve at 3M, 6M, 1Y, 2Y, 3Y, 5Y, 7Y, 10Y, 15Y, 20Y, 30Y (Svensson, continuous)\nz(T) linear between points, flat outside;  DF(T) = e^(−z(T)·T)', notes: { en: 'Used for EUR positions with no rate of their own: option and structured-product discounting, IRS annuities, swaption and cap/floor discounting, inflation swaps. The forward or par rate of a swap still comes from the position. A government curve sits somewhat below the swap (OIS) curve; for discounting the difference is second order.' }, params: 'rate, marketRate (position wins)' },
      { en: 'SEK discount curve', formula: 'points: SWESTR (overnight), Riksbank treasury bills 1M, 3M, 6M and benchmark government bond yields 2Y, 5Y, 7Y, 10Y\nz = ln(1 + y) (published yield taken as annual compounding);  z(T) linear between points, flat outside', notes: { en: 'Used for SEK positions with no rate of their own, as the EUR curve is for EUR. A simplification: the bond yields are yields of benchmark bonds, not bootstrapped zero-coupon rates, and bill rates are treated like the bond yields. For discounting at portfolio level the error is small; for pricing single long bonds it is not a substitute for a proper curve. A series the Riksbank does not deliver is left out; with no short or no 10-year point, or data older than a week, the SEK curve is not published and SEK positions fall back to their own rate.' }, params: 'rate, marketRate (position wins)' },
      { en: 'USD discount curve', formula: 'points: SOFR (overnight, New York Fed) and the US Treasury daily par yield curve 1M … 30Y\nz = 2·ln(1 + y/2) (par yields are quoted bond-equivalent, semi-annual);  z(T) linear between points, flat outside', notes: { en: 'The same simplification as for SEK: par yields are treated as zero rates, not bootstrapped. Last year\'s file is read as well, so early January still has data.' }, params: 'rate, marketRate (position wins)' },
      { en: 'NOK discount curve', formula: 'points: Norges Bank generic treasury bill (3M, 6M, 12M) and government bond (3Y, 5Y, 10Y) yields\nz = ln(1 + y);  z(T) linear between points, flat outside', notes: { en: 'No overnight point. Generic yields, not bootstrapped zero rates.' }, params: 'rate, marketRate (position wins)' },
      { en: 'Other currencies: your own sources', formula: 'a custom provider in market-sources.json: an https endpoint returning CSV or JSON (wide: one column per tenor; long: one row per date and tenor; or one download per tenor)\nz = continuous rate from the stated compounding (continuous, annual, semi-annual, quarterly, simple)', notes: { en: 'Tenors are those quoted on the newest date; a day counts when it has every one of them. EUR always comes from the ECB, and one currency has one source (the first listed). A provider that fails or does not pass the checks below is left out of the file; the curve already on a portfolio is then dropped and its positions use their own rate. API keys are read from the job\'s environment and never written to the file.' }, params: 'market-sources.json' },
      { en: 'Spread over the government curve', formula: 'spread = yield to maturity − (e^(z(T)) − 1),  T = years to maturity;  portfolio figure MV-weighted', notes: { en: 'Fixed-rate bonds in a currency with a published curve (EUR, SEK, USD, NOK, custom) only, not linkers or floaters, each on its own currency\'s curve. A G-spread: credit, liquidity and optionality over the government.' }, params: '' },
      { en: 'Checks before publishing', formula: '≥ 20 days and ≥ 20 currencies of FX;  USD 0.6–2.5 and SEK 5–25 per EUR;  every curve tenor present and between −3 % and 15 %;  €STR present;  newest date ≤ 7 days old\nevery other curve (SEK, USD, NOK, custom): ≥ 4 tenors incl. ≤ 6M and ≥ 10Y, rates −3 % to 15 %, overnight −2 % to 15 %, newest ≤ 7 days old', notes: { en: 'An ECB download that fails these is not published; the previous day\'s file stays in place. Any other provider that fails them (the SEK, USD, NOK or a custom curve) is only left out.' }, params: '' }
    ]
  },
  {
    id: 'fundRules', module: 'rules.js',
    title: { en: 'Fund rules' },
    intro: { en: 'Rules the user writes from the fund\'s own fund rules and prospectus. The engine checks exactly what is written; whether that captures the fund rules is the user\'s reading of them. Regulation and fund rules change; nothing here is legal advice.' },
    items: [
      { en: 'Matching holdings', formula: 'holding matches ⇔ every condition holds;  condition: field ∈ {values} | ∉ | contains | rating below/at least X\nfields: asset class, instrument type, group, region, country, sector, currency, issuer, strategy, rating (IG / HY / NR), name', notes: { en: 'Rating “below X” counts unrated holdings as below, the cautious reading. Region comes from the country code.' } },
      { en: 'Measures', formula: 'weight = Σ MV / NAV;  exposure = Σ net delta-adjusted exposure / NAV;  gross = Σ |exposure| / NAV\nlargest holding = max MV / NAV (derivatives left out);  largest group = max over groups of Σ MV / NAV\ncount = number of matches;  duration = −Σ DV01 / NAV / 1 bp', notes: { en: 'Status as for the UCITS limits: breach beyond the limit, warning within 10 % of it. The rules run through the same compliance check, so they appear on the dashboard, in pre-trade, in the breach history (active vs passive) and in the PDF.' } }
    ]
  },
  {
    id: 'globalExposure', module: 'globalexposure.js',
    title: { en: 'Global exposure: commitment or VaR approach' },
    intro: { en: 'The developer\'s reading of UCITS Directive art. 51(3) and the CESR/10-788 guidelines as of September 2026. The rules are updated continuously and can be read differently; this is an interpretation, not legal advice, and it may be wrong.' },
    items: [
      { en: 'VaR limit', formula: 'VaR = VaR(99 %, 1 day) · √20  from the back-cast P&L of today\'s holdings (historical simulation or EWMA), at least 250 days where available\nabsolute: VaR / NAV ≤ 20 %;  relative: VaR_fund / VaR_reference ≤ 2', notes: { en: 'The reference portfolio is a price series in the loaded history (an index or index fund standing for it); its VaR is taken from its returns with the same confidence, horizon and window. Without history the factor model gives an indicative figure, flagged. Under a VaR approach the commitment limit is not checked. History is cut at the valuation date, so past snapshots never use later prices.' }, params: 'globalExposure.method, absLimit, relLimit, model, window, reference' },
      { en: 'Backtest', formula: 'for each of the last 250 days t: VaR_t from days t−W … t−1;  overshooting ⇔ P&L_t < −VaR_t\nKupiec: LR = −2 ln[(1−p)^(n−x) p^x] + 2 ln[(1−x/n)^(n−x) (x/n)^x] ~ χ²(1)\nzone (250 days, 99 %): 0–4 green, 5–9 yellow, ≥ 10 red', notes: { en: 'Hypothetical backtest on today\'s holdings, so trades do not blur it. More than four overshootings at 99 % is read here as a signal to review the model; some supervisors expect notification.' } }
    ]
  },
  {
    id: 'lmt', module: 'lmt.js',
    title: { en: 'Liquidity management tools and swing pricing' },
    intro: { en: 'The developer\'s reading of Directive (EU) 2024/927 (applying from 16 April 2026) and ESMA\'s guidelines and RTS on liquidity management tools, as of September 2026. The rules are updated continuously and can be read differently; this is an interpretation, not legal advice, and it may be wrong.' },
    items: [
      { en: 'Selection', formula: 'selected tools among: gates, notice periods, redemption fees, swing pricing, dual pricing, anti-dilution levy, redemption in kind\nrequired: ≥ 2 (money market fund: ≥ 1);  suspension and side pockets are not counted', notes: { en: 'A flag is raised when more than one anti-dilution tool is selected, since as read here they should not be applied to the same dealing at the same time.' } },
      { en: 'Swing factor and dilution', formula: 'w_i = MV_i / Σ MV (non-derivative assets, cash at zero cost)\ncost_i = one-way cost (spread + commission + tax, bp) · stress multiplier + impact_i\nimpact_i = σ_daily,i · √(flow · |qty_i| / ADV_i)   (square-root law; stressed: σ × 1.5, ADV × 0.5)\nswing factor(flow) = Σ w_i cost_i;  dilution without swing = flow · factor / (1 − flow)\nthreshold = smallest flow where dilution ≥ materiality', notes: { en: 'Vertical slice: the flow is met pro rata. Default costs are rough placeholders per instrument type and should be replaced by the fund\'s own. The same number is the natural starting point for an anti-dilution levy or a redemption fee.' }, params: 'lmt.costs, stressMult, materialityBp, capPct, impact' },
      { en: 'Redemption gate', formula: 'paid on the first dealing day = min(request, gate);  deferred = request − gate;  dealing days = ⌈request / gate⌉\ncovered ⇔ assets sellable within 1 day ≥ first-day payment (normal and stressed liquidity profile)', notes: { en: 'A gate spreads a large outflow over several dealing days; it does not change what can be sold. Read it together with the liquidity stress test.' } }
    ]
  },
  {
    id: 'controlLog', module: 'auditlog.js',
    title: { en: 'Control log' },
    intro: { en: 'An append-only record per portfolio: sign-offs, breach cases and changes to the controls, each entry chained to the one before by a hash.' },
    items: [
      { en: 'Hash chain', formula: 'hash_n = SHA-256( canonical JSON of { seq, at, by, kind, valDate, data, prev = hash_(n−1) } ),  hash_0 = 64 zeros\nintact ⇔ for every n: seq_n = n, prev_n = hash_(n−1) and hash_n recomputes', notes: { en: 'Canonical JSON: keys sorted, so the order a file stores them in does not matter. SHA-256 is computed in the page itself (no dependency, works on plain-http intranet servers). Tamper-evident, not tamper-proof: whoever can edit the file can rebuild the whole chain, so keep the head hash somewhere else.' } },
      { en: 'Logged automatically', formula: 'any change through the app to: a UCITS limit (on/off, value), a fund rule (added, changed, removed), global exposure settings, liquidity tool settings\nundo: the change back is logged, flagged as undo; entries are never removed', notes: { en: 'Changes to holdings and prices are not logged here; the snapshots and Changes & track record cover those.' } },
      { en: 'Breach cases', formula: 'case = rule + start date;  state read from its entries: opened → notes → closed (or reopened)\na breach period is covered ⇔ a case of the same rule was opened on a date inside it (start ≤ case date ≤ end)\na breach today without a history period is covered ⇔ an open case of that rule exists', notes: { en: 'Breach periods, and whether each was active or passive, come from the limit history on Compliance (holdings on two or more dates). The cause on a case can be changed by a note; the original entry stays.' } },
      { en: 'Who', formula: 'by = the name typed on the Control log page, kept in this browser', notes: { en: 'No accounts, no server: the name is self-declared. Use one browser profile per person.' } }
    ]
  },
  {
    id: 'importModel', module: 'suggest.js · datachecks.js',
    title: { en: 'Import suggestions and data checks' },
    intro: { en: 'Two helpers around the import. Neither changes data by itself.' },
    items: [
      { en: 'Column and type-code suggestions', formula: 'features: character 3- and 4-grams and words of the header, plus sample-value shapes (date, ISIN, currency, rating, magnitude, integer, 0–1, near par)\nhashed into 16 384 buckets;  p = softmax(W x + b)\nsuggest the best field not yet mapped when p ≥ 50 %;  "unrelated column" is a class of its own', notes: { en: 'Multinomial logistic regression trained offline, and only on the platform\'s own field registry: every label and alias, varied the way exports vary them (abbreviations, prefixes, currency suffixes, typos, casing) with synthetic sample values. No user file is ever used; the model file ships with the site. On a hand-written set of unseen headers it gets about 9 in 10 right. A suggestion is shown next to the column and only applied when accepted; type codes stay unvalued until mapped.' } },
      { en: 'Data checks on a new file', formula: 'matched on ISIN → ticker → name against the previous holdings\nunit error: price ratio ≈ 100 or 0.01 (±15 %);  quantity scale: ratio ≈ 10^±2, 10^±3\njump: |log return| > 6 · 1.4826 · MAD of the series\' daily log returns · √days, and above a floor per asset class\nstale: price unchanged over ≥ 5 days while the rest of the file moved\nalso: price missing or ≤ 0, currency changed, long ↔ short, a large holding gone', notes: { en: 'Robust statistics (median absolute deviation) so one bad day in the history does not hide the next. Without enough history the cross-section of the file is used instead: a move far outside what the other holdings of the same asset class did that day. Flags only; the file is imported as it is if you go ahead.' } }
    ]
  },
  {
    id: 'data', module: 'store.js · importer.js · filelink.js',
    title: { en: 'Data, sources and storage' },
    items: [
      { en: 'Prices and reported figures', formula: 'entered by hand or imported from your files (CSV, TSV, Excel, JSON, XML)', notes: { en: 'Nothing is fetched from brokers, custodians or market-data vendors. Reported notional and delta come from the same files.' } },
      { en: 'FX rates', formula: 'stored as EUR crosses;  base per CCY = EUR/base ÷ EUR/CCY', notes: { en: 'ECB reference rates read from the ECB\'s own file (eurofxref CSV or XML, downloaded by you), a built-in fallback table, or your own rates in Settings. Historical FX for the back-cast comes from series named CCY+BASE in the price history.' } },
      { en: 'Storage', formula: 'browser IndexedDB (this device only; localStorage where IndexedDB is unavailable) + optional linked file on your computer + backup files', notes: { en: 'Nothing is sent to a server. Charts, PDF and Excel libraries are loaded from a CDN with integrity hashes, so a changed file is refused.' } }
    ]
  }
];
