// Every calculation the platform makes, in one place, so a risk manager or auditor can check the
// method without reading the code. Plain data: the Methodology page renders it, and the test
// checks that every section names the module the numbers come from.
//
// Each item: { en, sv } for the name, `formula` (plain text / Unicode maths, not translated),
// { en, sv } notes, and optionally `params` — the settings or fields the calculation reads.
export const METHODOLOGY = [
  {
    id: 'valuation', module: 'instruments.js · pricing.js',
    title: { en: 'Valuation per instrument', sv: 'Värdering per instrument' },
    intro: { en: 'Every position returns market value (MV), gross exposure, signed net exposure and its sensitivities in the base currency. Amounts in other currencies are converted at the FX table (ECB reference rates or your own).', sv: 'Varje innehav ger marknadsvärde (MV), bruttoexponering, nettoexponering med tecken och känsligheter i basvalutan. Belopp i andra valutor räknas om med valutatabellen (ECB:s referenskurser eller egna).' },
    items: [
      { en: 'Equity, ETF, fund, commodity (ETC), alternative', sv: 'Aktie, ETF, fond, råvara (ETC), alternativ', formula: 'MV = quantity × price × FX', notes: { en: 'Exposure = |MV|. Equity delta = MV. Funds and ETFs: the look-through class decides whether the MV counts as equity delta, duration (via the duration field) or commodity delta; a mixed fund uses the equity share.', sv: 'Exponering = |MV|. Aktiedelta = MV. Fonder och ETF:er: genomlyst tillgångsslag avgör om MV räknas som aktiedelta, duration (via durationsfältet) eller råvarudelta; en blandfond använder aktieandelen.' } },
      { en: 'Fixed-coupon bonds (government, corporate)', sv: 'Obligationer med fast kupong (stat, företag)', formula: 'Dirty = Σ CF_i · (1 + y/f)^(−n_i)   with n_i = i + w,  w = days to next coupon / days in period\nMV = nominal × dirty / 100 × FX;  accrued = coupon/f × (1 − w)', notes: { en: 'Street convention on a coupon schedule rolled back from maturity (unadjusted). From a clean price the yield is solved with Newton–Raphson (bisection fallback); from a yield the price follows. A zero coupon is the same formula with no coupons.', sv: 'Marknadskonvention på ett kupongschema räknat bakåt från förfall (ojusterat). Från ren kurs löses avkastningen med Newton–Raphson (bisektion som reserv); från avkastning följer kursen. Nollkupongare är samma formel utan kuponger.' }, params: 'price (clean %), yield %, coupon %, freq, maturity' },
      { en: 'Duration and convexity', sv: 'Duration och konvexitet', formula: 'Macaulay D = Σ t_i · PV_i / P;   modified D = D / (1 + y/f)\nConvexity = Σ CF_i · disc_i · n_i(n_i+1) / (f² · P · (1+y/f)²)', notes: { en: 'Per-100 figures, then applied to MV. DV01 per position = −MV × modified duration × 1e−4.', sv: 'Per 100, därefter applicerat på MV. DV01 per innehav = −MV × modifierad duration × 1e−4.' } },
      { en: 'Floating rate notes', sv: 'FRN (rörlig kupong)', formula: 'rate duration = min(years to maturity, 1/f);  spread duration = modified duration at the current coupon', notes: { en: 'Valued as a bond at the current coupon. The rate duration only runs to the next reset; the credit (spread) duration runs to maturity.', sv: 'Värderas som obligation på aktuell kupong. Räntedurationen löper bara till nästa räntesättning; kredit- (spread-) durationen till förfall.' } },
      { en: 'Money market / T-bills', sv: 'Penningmarknad / statsskuldväxlar', formula: 'zero-coupon bond formula with coupon = 0', notes: { en: 'Government if the issuer name says so (state, treasury, Riksgälden…); otherwise it carries spread duration and counts against the issuer limit.', sv: 'Stat om emittentnamnet säger det (stat, treasury, Riksgälden…); annars bär den spreadduration och räknas mot emittentgränsen.' } },
      { en: 'Cash / deposits', sv: 'Kassa / inlåning', formula: 'MV = amount × FX', notes: { en: 'Negative for overdrafts or unsettled payables.', sv: 'Negativt för checkkredit eller olikviderade skulder.' } },
      { en: 'Futures', sv: 'Terminer (futures)', formula: 'notional = contracts × price × multiplier × FX;  MV = unsettled variation margin\nexposure = |notional|;  net = notional (signed)', notes: { en: 'Daily margined, so the market value is only the unsettled variation margin (the MTM field); a file value above a quarter of the notional is taken to be the notional, ignored and flagged. Equity: delta = notional, beta from the field. Bond futures: DV01 = −notional × CTD duration × 1e−4. Commodity: commodity delta = notional. FX futures: long the traded currency, short the quote currency. A reported notional replaces the model notional when present and the setting is on.', sv: 'Aktie: delta = nominellt, beta från fältet. Marginalavräknas dagligen, så marknadsvärdet är bara orealiserad variationsmarginal (fältet för marknadsvärde); ett värde i filen över en fjärdedel av nominellt belopp tolkas som nominellt, ignoreras och flaggas. Obligationsterminer: DV01 = −nominellt × CTD-duration × 1e−4. Råvara: råvarudelta = nominellt. Valutaterminer: lång handlad valuta, kort motvaluta. Rapporterat nominellt värde ersätter modellens när det finns och inställningen är på.' } },
      { en: 'Options (Black-Scholes-Merton / Black-76 / Garman-Kohlhagen)', sv: 'Optioner (Black-Scholes-Merton / Black-76 / Garman-Kohlhagen)', formula: 'd1 = [ln(S/K) + (r − q + σ²/2)T] / (σ√T),  d2 = d1 − σ√T\nCall = S e^(−qT) N(d1) − K e^(−rT) N(d2);  Put = K e^(−rT) N(−d2) − S e^(−qT) N(−d1)\nΔ_call = e^(−qT) N(d1);  Γ = e^(−qT) φ(d1) / (S σ √T);  vega = S e^(−qT) φ(d1) √T / 100 (per vol point);  θ per day', notes: { en: 'q = dividend yield for equities, the foreign rate for FX (Garman-Kohlhagen), and q = r for rates and commodities (Black-76 on a forward). MV = the market value in your file if given, else contracts × multiplier × premium, else the model price (flagged). An option with a counterparty in Issuer is OTC and counts toward the OTC counterparty limit. Delta-adjusted exposure = contracts × multiplier × Δ × S × FX; that is what exposure, net, equity delta and the commitment use. Cash gamma = units × Γ × S². Reported delta (0.45 or 45 %) or reported delta-adjusted exposure overrides the model when present: magnitudes from the file, signs from long/short and call/put. Flagged when the implied delta differs from the model by more than 0.05 or the notional by more than 10 %.', sv: 'q = utdelningsyield för aktier, utländsk ränta för valuta (Garman-Kohlhagen) och q = r för räntor och råvaror (Black-76 på en forward). MV = marknadsvärdet i din fil om det finns, annars kontrakt × multiplikator × premie, annars modellpriset (flaggas). En option med motpart som emittent är OTC och räknas mot gränsen för OTC-motparter. Deltajusterad exponering = kontrakt × multiplikator × Δ × S × FX; det används för exponering, netto, aktiedelta och åtagande. Kontantgamma = enheter × Γ × S². Rapporterad delta (0,45 eller 45 %) eller rapporterad deltajusterad exponering ersätter modellen när den finns: storlek från filen, tecken från lång/kort och köp/sälj. Flaggas när implicit delta avviker mer än 0,05 från modellen eller nominellt belopp mer än 10 %.' }, params: 'strike, maturity, underlyingPrice, vol %, rate %, divYield %, multiplier, reportedDelta, reportedNotional, reportedDeltaExposure' },
      { en: 'FX forwards / swaps', sv: 'Valutaterminer / swappar', formula: 'MV = buy amount × FX_buy − sell amount × FX_sell  (or the entered market value)\nexposure = max(|buy|, |sell|);  net = 0', notes: { en: 'Without the counterparty\'s MTM, spot valuation: forward points and discounting are ignored, which is material for long-dated hedges between currencies with different rates, so the position is flagged. Give the MTM. The two legs feed the currency table as a hedge.', sv: 'Utan motpartens marknadsvärde: spotvärdering där terminspunkter och diskontering ignoreras, vilket är väsentligt för långa säkringar mellan valutor med olika räntor, så positionen flaggas. Ange marknadsvärdet. De två benen går in i valutatabellen som säkring.' } },
      { en: 'Interest rate swaps', sv: 'Ränteswappar', formula: 'A = Σ (1/f) · (1 + s/f)^(−n_i)   (annuity at the current par rate s)\nMV ≈ ±N × (fixed − s) × A   (+ receive fixed, − pay fixed)\nDV01 = ∓N × A × 1e−4', notes: { en: 'Single flat curve at the entered par rate; an entered market value overrides the estimate. Receive fixed adds duration, pay fixed removes it. Notional counts as fixed-income exposure with the same sign.', sv: 'En platt kurva på angiven swapränta; angivet marknadsvärde ersätter uppskattningen. Erhåll fast ger duration, betala fast tar bort den. Nominellt belopp räknas som ränteexponering med samma tecken.' } },
      { en: 'Credit default swaps', sv: 'Kreditswappar (CDS)', formula: 'A = risky annuity at (2.5 % + market spread), quarterly\nMV ≈ ±N × (market spread − contract spread) × 1e−4 × A   (+ bought protection)\nCS01 = ±N × A × 1e−4;  net exposure = −N for bought, +N for sold protection', notes: { en: 'Selling protection is long credit (like owning the bond without funding it) and counts toward the issuer limit; buying protection gains when spreads widen.', sv: 'Att sälja skydd är lång kreditrisk (som att äga obligationen utan att finansiera den) och räknas mot emittentgränsen; att köpa skydd ger vinst när spreadar vidgas.' } }
    ]
  },
  {
    id: 'exposure', module: 'analytics.js · allocation.js',
    title: { en: 'Exposure and asset allocation', sv: 'Exponering och tillgångsfördelning' },
    items: [
      { en: 'NAV, gross and net exposure', sv: 'NAV, brutto- och nettoexponering', formula: 'NAV = Σ MV;  gross = Σ exposure / NAV;  net = Σ net exposure / NAV\ncommitment = Σ exposure of derivatives / NAV', notes: { en: 'Commitment approach: futures and swaps at notional, options delta-adjusted, FX forwards at the larger leg. No netting of hedges, so it is conservative against the UCITS 100 % limit.', sv: 'Åtagandemetoden: terminer och swappar till nominellt belopp, optioner deltajusterat, valutaterminer till det större benet. Ingen nettning av säkringar, alltså konservativt mot UCITS-gränsen 100 %.' } },
      { en: 'Allocation at market value', sv: 'Fördelning till marknadsvärde', formula: 'weight_class = Σ MV in class / NAV', notes: { en: 'Sector excludes cash, FX forwards, swaps and government bonds; region uses the country code; issuer uses the issuer field (name if empty).', sv: 'Sektor exkluderar kassa, valutaterminer, swappar och statsobligationer; region använder landskoden; emittent använder emittentfältet (namn om tomt).' } },
      { en: 'Economic exposure per asset class', sv: 'Ekonomisk exponering per tillgångsslag', formula: 'economic = physical MV + derivative overlay\noverlay = Σ (net exposure − MV) of derivatives on the class', notes: { en: 'Futures and swaps at signed notional, options at delta-adjusted exposure, sold CDS = long credit. Mixed funds are split by equity share. FX forwards and FX options are currency hedges, not asset-class bets, so only their MTM counts here. Interest-rate derivatives are at notional, not duration-weighted.', sv: 'Terminer och swappar till nominellt belopp med tecken, optioner deltajusterat, såld CDS = lång kredit. Blandfonder delas efter aktieandel. Valutaterminer och valutaoptioner är valutasäkringar, inte tillgångsslagsbeslut, så bara deras marknadsvärde räknas här. Räntederivat till nominellt belopp, inte durationsviktat.' } },
      { en: 'Mandate check', sv: 'Mandatkontroll', formula: 'status = breach if economic weight < min or > max;  warning within 2 percentage points of a limit;  active = economic − target', notes: { en: 'Targets and ranges are entered per class in % of NAV.', sv: 'Mål och intervall anges per tillgångsslag i % av NAV.' } },
      { en: 'Concentration', sv: 'Koncentration', formula: 'HHI = Σ w_i²  over non-cash, non-derivative holdings;  effective N = 1 / HHI;  top 10 = Σ of the ten largest weights', notes: { en: '', sv: '' } },
      { en: 'Currency exposure', sv: 'Valutaexponering', formula: 'gross_ccy = Σ MV of holdings in ccy (options at MV, futures at margin)\nhedge_ccy = Σ legs of FX forwards, FX futures and FX options in ccy\nnet = gross + hedge;  hedge ratio = −hedge / gross', notes: { en: 'Everything in base-currency terms; the base currency itself is not shown.', sv: 'Allt i basvalutatermer; basvalutan själv visas inte.' } }
    ]
  },
  {
    id: 'fixedIncome', module: 'analytics.js',
    title: { en: 'Fixed income', sv: 'Räntebärande' },
    items: [
      { en: 'Portfolio figures', sv: 'Portföljmått', formula: 'YTM, modified duration, spread duration, convexity = MV-weighted averages over bonds, FRNs and money market\nportfolio duration = −Σ DV01 / NAV / 1e−4  (derivatives and funds included)\nportfolio spread duration = −Σ CS01 / NAV / 1e−4', notes: { en: 'The weighted averages describe the bond book; the portfolio durations describe the whole fund and therefore include swaps, bond futures, CDS and bond funds.', sv: 'De viktade snitten beskriver obligationsboken; portföljdurationerna beskriver hela fonden och inkluderar därför swappar, obligationsterminer, CDS och räntefonder.' } },
      { en: 'Maturity and DV01 ladders', sv: 'Löptids- och DV01-stegar', formula: 'buckets 0–1, 1–3, 3–5, 5–7, 7–10, 10+ years by years to maturity', notes: { en: 'The MV ladder covers bonds only; the DV01 ladder also places swaps and futures, so a receiver swap or a short bond future shows up.', sv: 'MV-stegen täcker bara obligationer; DV01-stegen placerar även swappar och terminer, så en receiverswap eller kort obligationstermin syns.' } },
      { en: 'Average rating', sv: 'Snittrating', formula: 'score AAA=1 … D=22; average = MV-weighted score, mapped back to the nearest notch\nhigh yield = rating below BBB−', notes: { en: 'Linear average of notches, which is the common simplification (agencies use non-linear scales).', sv: 'Linjärt snitt av steg, den vanliga förenklingen (kreditinstituten använder icke-linjära skalor).' } }
    ]
  },
  {
    id: 'risk', module: 'analytics.js (factorModel, historicalRisk)',
    title: { en: 'Risk: VaR, expected shortfall, volatility', sv: 'Risk: VaR, expected shortfall, volatilitet' },
    items: [
      { en: 'Parametric (factor) model', sv: 'Parametrisk (faktor-) modell', formula: 'factors: equity, credit (bp), commodity, volatility (vol points), rates per currency (bp), FX per currency\ns_k = Σ_i sensitivity_i,k   (equity: delta × beta; rates: DV01; credit: CS01; FX: amount; vol: vega; commodity: delta)\nσ² = sᵀ Σ s + Σ_i (specific vol × |equity delta_i|)²,   Σ_kl = ρ_kl σ_k σ_l\nVaR = z_c · σ · √(h/252);  ES = σ · √(h/252) · φ(z_c) / (1 − c)', notes: { en: 'Delta-normal: linear in the factors, gamma ignored. Vols and correlations are the capital-market assumptions in Settings. Contributions per factor group and per position are Euler contributions s_k (Σ s)_k / σ, so they add up to the total. The asset-class view sums the same contributions per position class: equity = equity market + stock-specific + implied vol of equity options + equity derivatives; fixed income = rates + credit + rate/credit derivatives; currency = the FX factors of every position (holdings and hedges together).', sv: 'Delta-normal: linjär i faktorerna, gamma ignoreras. Volatiliteter och korrelationer är antagandena i Inställningar. Bidrag per faktorgrupp och per innehav är Euler-bidrag s_k (Σ s)_k / σ, så de summerar till totalen. Vyn per tillgångsslag summerar samma bidrag per innehavets tillgångsslag: aktier = aktiemarknad + bolagsspecifikt + implicit vol i aktieoptioner + aktiederivat; räntor = räntor + kredit + ränte-/kreditderivat; valuta = valutafaktorerna för alla innehav (innehav och säkringar tillsammans).' }, params: 'confidence, horizonDays, CMA vols and correlations, equitySpecificVol, beta' },
      { en: 'Historical simulation', sv: 'Historisk simulering', formula: 'P&L_t = Σ_i exposure_i × [(1 + r_i,t)(1 + fx_i,t) − 1]   (futures/options at delta-adjusted exposure, others at MV)\nVaR = −quantile_(1−c)(P&L) · √h;  ES = −mean(P&L ≤ quantile) · √h;  vol = stdev(P&L) · √252 / NAV', notes: { en: 'Back-cast: today\'s positions on the price history you upload (matched by ISIN, ticker or name; FX series as CCY+BASE). Coverage = covered exposure / risky NAV. Positions without a series are listed as uncovered. Used as the headline when coverage ≥ 70 % and ≥ 120 observations (or when chosen in Settings).', sv: 'Back-cast: dagens innehav på kurshistoriken du laddar upp (matchas på ISIN, ticker eller namn; valutaserier som CCY+BAS). Täckning = täckt exponering / riskfylld NAV. Innehav utan serie listas som otäckta. Används som huvudmått när täckningen är ≥ 70 % och ≥ 120 observationer (eller när det valts i Inställningar).' } },
      { en: 'Correlation matrix and rolling volatility', sv: 'Korrelationsmatris och rullande volatilitet', formula: 'Pearson correlation of daily returns for the 12 largest covered positions;  rolling vol = stdev over 63 trading days · √252', notes: { en: '', sv: '' } }
    ]
  },
  {
    id: 'performance', module: 'analytics.js (perfStats)',
    title: { en: 'Performance statistics', sv: 'Avkastningsmått' },
    items: [
      { en: 'Return and risk', sv: 'Avkastning och risk', formula: 'total = Π(1 + r_t) − 1;  CAGR = (1 + total)^(252/n) − 1;  vol = stdev(r) · √252\nSharpe = (CAGR − rf) / vol;  Sortino = (CAGR − rf) / downside,  downside = √(Σ min(0, r_t − rf/252)² / n) · √252\nmax drawdown = min(NAV_t / peak_t − 1);  Calmar = CAGR / |max DD|', notes: { en: 'Daily returns are the back-cast portfolio return (P&L / NAV). VaR 95/99 and ES are empirical quantiles of the daily returns. Skew and excess kurtosis are population moments.', sv: 'Dagsavkastningarna är back-castad portföljavkastning (P&L / NAV). VaR 95/99 och ES är empiriska kvantiler av dagsavkastningarna. Skevhet och excess-kurtosis är populationsmoment.' }, params: 'riskFree %' },
      { en: 'Against the benchmark', sv: 'Mot jämförelseindex', formula: 'β = cov(r, b) / var(b);  α = (CAGR − rf) − β (CAGR_b − rf)\ntracking error = stdev(r − b) · √252;  information ratio = (CAGR − CAGR_b) / TE\nup/down capture = mean(r | b > 0) / mean(b | b > 0), likewise for b < 0', notes: { en: 'The benchmark is a price series in the history named in Settings.', sv: 'Jämförelseindex är en kursserie i historiken som pekas ut i Inställningar.' } },
      { en: 'Risk–return map (3D)', sv: 'Risk–avkastningskarta (3D)', formula: 'per position over the window: return = Π(1 + r_t) − 1;  vol = stdev(r) · √252;  contribution = cov(P&L_i, P&L_port) / stdev(P&L_port) · √252 / NAV\nr_t = P&L_t / exposure (delta-adjusted for futures and options)', notes: { en: 'Marker size is exposure as % of NAV, colour the asset class. Window 3 months, 1 year or the whole history.', sv: 'Markörstorlek är exponering i % av NAV, färg tillgångsslaget. Fönster 3 månader, 1 år eller hela historiken.' } },
      { en: 'Monthly table', sv: 'Månadstabell', formula: 'month = Π(1 + r_t) − 1 over the month;  YTD = Π(1 + month) − 1', notes: { en: '', sv: '' } }
    ]
  },
  {
    id: 'stress', module: 'analytics.js (runStress) · instruments.js (stressPnl)',
    title: { en: 'Stress tests', sv: 'Stresstester' },
    items: [
      { en: 'Scenario shocks', sv: 'Scenariochocker', formula: 'each scenario = { equity %, rates bp, credit spread bp, all foreign currencies %, commodities %, volatility points }', notes: { en: 'Stylised calibrations of well-known episodes (2008, 2011, 2020, 2022) plus single-factor shocks; not replays of history.', sv: 'Stiliserade kalibreringar av kända episoder (2008, 2011, 2020, 2022) plus enfaktorchocker; inte återspelningar av historien.' } },
      { en: 'P&L per position', sv: 'Resultat per innehav', formula: 'P&L = Δ_eq · β · eq + Δ_cmd · cmd + vega · vol + ½ Γ eq² + Σ DV01_ccy · rates + CS01 · cs + ½ MV · convexity · dy²\nthen translation: P&L × fx_move + Σ currency exposure × fx_move', notes: { en: 'Options are fully repriced instead (BSM at the shocked underlying, rate and vol; rate and credit options move the underlying by −duration × shock). The cross term converts the local P&L at the shocked FX rate.', sv: 'Optioner prissätts i stället om fullt ut (BSM på chockad underliggande, ränta och vol; ränte- och kreditoptioner flyttar underliggande med −duration × chock). Korstermen räknar om det lokala resultatet till chockad valutakurs.' } }
    ]
  },
  {
    id: 'liquidity', module: 'analytics.js (liquidity) · insights.js (liquidityStress)',
    title: { en: 'Liquidity', sv: 'Likviditet' },
    items: [
      { en: 'Days to liquidate', sv: 'Dagar att avveckla', formula: 'days = ⌈ |quantity| / (ADV × participation) ⌉   when ADV is given\notherwise the instrument\'s liquidity field, else a default per type (equity 2, ETF 1, bonds 3, alternatives 180 …)', notes: { en: 'Stressed profile: half the participation rate and 1.5 × the type-based days.', sv: 'Stressad profil: halva deltagandegraden och 1,5 × typbaserade dagar.' }, params: 'participation %, adv, liquidityDays' },
      { en: 'Liquidity profile', sv: 'Likviditetsprofil', formula: 'liquid within h days = Σ MV_i × min(1, h / days_i)', notes: { en: 'Pro-rata: a position that needs 10 days is 70 % sold by day 7. Illiquid = more than 90 days.', sv: 'Pro rata: ett innehav som behöver 10 dagar är sålt till 70 % efter 7 dagar. Illikvitt = mer än 90 dagar.' } },
      { en: 'Liquidity stress test (ESMA)', sv: 'Likviditetsstresstest (ESMA)', formula: 'sellable(h) = Σ MV_i · min(1, h / days_i)\ncoverage = sellable(h) / (R × NAV)   — met when ≥ 1\nwaterfall: sell in order of days_i until R × NAV;   vertical: every asset × (1 − R)', notes: { en: 'Follows ESMA\'s Guidelines on liquidity stress testing in UCITS and AIFs (redemption shock, coverage ratio, effect on the remaining investors). Derivatives are not sold, so commitment rises as NAV falls; limits are re-checked on the portfolio left behind. Market impact of the sales is not modelled.', sv: 'Följer ESMA:s riktlinjer för likviditetsstresstester i UCITS och AIF (inlösenchock, täckningsgrad, effekt på kvarvarande andelsägare). Derivat säljs inte, så åtagandet stiger när NAV faller; reglerna kontrolleras på portföljen som blir kvar. Kurspåverkan av försäljningarna modelleras inte.' }, params: 'redemption shock, horizon, normal/stressed' }
    ]
  },
  {
    id: 'compliance', module: 'analytics.js (compliance)',
    title: { en: 'Investment rules', sv: 'Placeringsregler' },
    items: [
      { en: 'Issuer limits (UCITS-style)', sv: 'Emittentgränser (UCITS-stil)', formula: 'issuer exposure = Σ MV of equities, corporate bonds, FRNs, non-government money market, alternatives, commodities + notional of sold CDS\nmax issuer ≤ 10 %;  Σ issuers above 5 % ≤ 40 %;  government issuer ≤ 35 %;  bank deposits ≤ 20 %;  single fund ≤ 20 %', notes: { en: 'Status: breach above the limit, warning above 90 % of it (below 110 % for minimum rules). Group-of-issuer aggregation, look-through and collateral netting are not applied. A CDS on an index (iTraxx, CDX) is left out of the issuer limits, as UCITS art. 51(3) allows for derivatives on financial indices.', sv: 'Status: brott över gränsen, varning över 90 % av den (under 110 % för minimiregler). Koncernaggregering, genomlysning och säkerhetsnettning tillämpas inte. En CDS på ett index (iTraxx, CDX) räknas inte in i emittentgränserna, vilket UCITS art. 51.3 tillåter för derivat på finansiella index.' }, params: 'limits (on/off and value per rule)' },
      { en: 'Other rules', sv: 'Övriga regler', formula: 'commitment ≤ 100 %;  OTC counterparty (positive MTM of forwards, swaps, CDS) ≤ 10 %;  optional: single position, sector, high yield, 7-day liquidity ≥, cash ≥, illiquid ≤', notes: { en: '', sv: '' } }
    ]
  },
  {
    id: 'oversight', module: 'insights.js · snapshots.js',
    title: { en: 'Changes, track record and limit history', sv: 'Förändringar, historik och regelhistorik' },
    intro: { en: 'Built on the holdings on each date: the dates in a connected file, or snapshots you save. Every date is valued with today\'s FX table and settings.', sv: 'Bygger på innehaven per datum: datumen i en kopplad fil, eller ögonblicksbilder du sparar. Varje datum värderas med dagens valutatabell och inställningar.' },
    items: [
      { en: 'Holdings-based return', sv: 'Innehavsbaserad avkastning', formula: 'r(A→B) = V(holdings_A at prices_B) / V(holdings_A at prices_A) − 1\ntrack record = Π (1 + r_t) − 1  over consecutive snapshots', notes: { en: 'What the holdings on the first date earned, so subscriptions, redemptions and intra-period trades do not distort it. Futures add their variation margin and bonds the coupons paid in the period, both of which settle into cash. A holding sold before date B is priced from the price history (last price on or before B) or, failing that, at its old price and flagged. Returns for spans under a year are not annualised (GIPS).', sv: 'Vad innehaven på första datumet tjänade, så teckningar, inlösen och affärer under perioden påverkar inte. Terminer lägger till sin variationsmarginal och obligationer kupongerna som betalats under perioden, eftersom båda avräknas mot kassan. Ett innehav som sålts före datum B prissätts från kurshistoriken (senaste kurs på eller före B) eller, om den saknas, till sin gamla kurs och flaggas. Avkastning för perioder kortare än ett år anges inte i årstakt (GIPS).' }, params: 'snapshots, price history, FX table' },
      { en: 'Price and trading effect, flows, turnover', sv: 'Pris- och affärseffekt, flöden, omsättning', formula: 'price effect_i = MV_i(A holdings, B prices) − MV_i(A)\ntrade effect_i = MV_i(B) − MV_i(A holdings, B prices)\nnet flows ≈ NAV_B − V(holdings_A at prices_B)\nturnover = min(Σ buys, Σ sells) / average NAV   (cash and derivatives excluded)', notes: { en: 'Trades between securities and cash cancel in the flow estimate, so what remains is money in or out, fees and distributions paid. Contribution per holding = price effect / NAV_A; summed arithmetically over periods.', sv: 'Affärer mellan värdepapper och kassa tar ut varandra i flödesuppskattningen, så det som återstår är pengar in eller ut, avgifter och utbetalda utdelningar. Bidrag per innehav = priseffekt / NAV_A; summeras aritmetiskt över perioderna.' } },
      { en: 'Active vs passive limit breaches', sv: 'Aktiva och passiva regelbrott', formula: 'for each date t:  check(holdings_t)  and  check(holdings_{t−1} at prices_t)\nbreach starts at t:  passive if the second check also breaches, else active', notes: { en: 'Passive: the unchanged portfolio would have breached anyway (market moves, or flows). Active: the trades did it. UCITS art. 57(2): a passive breach is remedied as a priority objective, taking due account of unitholders\' interests; an active breach at once. Today\'s limits are applied to every date.', sv: 'Passivt: den oförändrade portföljen hade brutit ändå (kursrörelser eller flöden). Aktivt: affärerna orsakade det. UCITS art. 57.2: ett passivt brott rättas med förtur med hänsyn till andelsägarnas intressen; ett aktivt omedelbart. Dagens regler tillämpas på alla datum.' } }
    ]
  },
  {
    id: 'pretrade', module: 'insights.js (whatIf, applyTrades)',
    title: { en: 'Pre-trade what-if', sv: 'Pre-trade-analys' },
    items: [
      { en: 'Applying trades', sv: 'Affärer', formula: 'target weight w:  q_new = w × NAV / (MV / q)\nchange Δq:  q_new = q + Δq;   new quantity:  q_new = value\ncash_new = cash − Σ ΔMV / FX_cash', notes: { en: 'All size fields scale together (quantity, legs, MTM, reported figures). Trades are at current prices without costs or market impact; the before/after figures use the parametric model so they are comparable.', sv: 'Alla storleksfält skalas tillsammans (antal, ben, MTM, rapporterade värden). Affärerna görs till aktuella kurser utan kostnader eller marknadspåverkan; före/efter-siffrorna använder den parametriska modellen så att de är jämförbara.' }, params: 'holdings, cash account' }
    ]
  },
  {
    id: 'attribution', module: 'insights.js (brinson, portfolioSegments)',
    title: { en: 'Performance attribution', sv: 'Avkastningsattribution' },
    items: [
      { en: 'Brinson-Fachler', sv: 'Brinson-Fachler', formula: 'allocation_i  = (wp_i − wb_i) · (Rb_i − Rb)\nselection_i   = wb_i · (Rp_i − Rb_i)\ninteraction_i = (wp_i − wb_i) · (Rp_i − Rb_i)\nΣ_i (allocation + selection + interaction) = Rp − Rb', notes: { en: 'Single period, market-value weights at the start. Portfolio side from two snapshots (holdings-based) or, without snapshots, today\'s holdings over the price history. A segment only the portfolio holds takes Rb_i = Rb (its effect is interaction); one only the benchmark holds takes Rp_i = Rb_i (its effect is allocation). Segments under 0.1 % of NAV go to a residual so totals reconcile.', sv: 'En period, marknadsvärdesvikter vid start. Portföljsidan från två ögonblicksbilder (innehavsbaserad) eller, utan dem, dagens innehav över kurshistoriken. Ett segment bara portföljen har får Rb_i = Rb (effekten blir samspel); ett bara index har får Rp_i = Rb_i (effekten blir allokering). Segment under 0,1 % av NAV läggs i en rest så att summorna stämmer.' }, params: 'benchmark weight and return per segment' }
    ]
  },
  {
    id: 'pnl', module: 'pnl.js',
    title: { en: 'Cost basis and P&L', sv: 'Anskaffningsvärde och resultat' },
    items: [
      { en: 'Average cost (transaction log)', sv: 'Genomsnittligt anskaffningsvärde (transaktionslogg)', formula: 'buy:  avg ← (q · avg + Δq · (price·unit + fees/Δq)) / (q + Δq)\nsell: realised = Δq · (price·unit − avg) − fees;  q ← q − Δq  (avg unchanged)\nselling through zero opens a short at the trade price; covering a short realises (avg − price)', notes: { en: 'Average-cost method (the Swedish tax standard, "genomsnittsmetoden"); FIFO is not offered. unit = 1 for shares and fund units, multiplier for options, 1/100 for bonds and bills (price in % of par). Quantities are signed so short positions work symmetrically. The book quantity is compared with the position; a difference is flagged, not corrected.', sv: 'Genomsnittsmetoden (skattestandard i Sverige); FIFO erbjuds inte. unit = 1 för aktier och fondandelar, multiplikator för optioner, 1/100 för obligationer och växlar (kurs i % av nominellt). Kvantiteter har tecken så korta positioner fungerar symmetriskt. Bokens antal jämförs med innehavet; en skillnad flaggas, rättas inte.' }, params: 'transactions: date, side, qty, price, fees, fx' },
      { en: 'Cost price without transactions', sv: 'Anskaffningsvärde utan transaktioner', formula: 'cost basis = quantity × costPrice × unit × FX_today', notes: { en: 'For holdings loaded from a custodian file. With today\'s FX there is no FX effect to show.', sv: 'För innehav från en depåfil. Med dagens valutakurs finns ingen valutaeffekt att visa.' }, params: 'costPrice' },
      { en: 'Unrealised P&L and FX effect', sv: 'Orealiserat resultat och valutaeffekt', formula: 'unrealised = MV − cost basis (base ccy)\nlocal part = (price·unit − avg) × q × FX_today;  FX effect = unrealised − local part', notes: { en: 'The FX effect only appears when transactions carry the FX rate of the trade day (cost basis in base currency = Σ q · price · FX_trade). Bond MV is dirty, cost is clean, so accrued interest sits in the unrealised figure. Futures, swaps and forwards are outside the cost basis (no purchase price); their MTM is in the holdings.', sv: 'Valutaeffekten syns bara när transaktionerna har affärsdagens valutakurs (anskaffningsvärde i basvaluta = Σ q · kurs · FX_affärsdag). Obligationers MV är smutsig kurs, anskaffningen ren, så upplupen ränta ligger i det orealiserade. Terminer, swappar och valutaterminer ligger utanför anskaffningsvärdet (inget inköpspris); deras marknadsvärde finns i innehaven.' } },
      { en: 'Realised P&L per period', sv: 'Realiserat resultat per period', formula: 'Σ realised of sells with trade date ≥ period start (YTD, 12 months, all)', notes: { en: 'In base currency at the trade-day FX when recorded, else today\'s.', sv: 'I basvaluta till affärsdagens valutakurs när den finns, annars dagens.' } }
    ]
  },
  {
    id: 'fund', module: 'fund.js',
    title: { en: 'Fund calculations', sv: 'Fondberäkningar' },
    items: [
      { en: 'Cash-flow calendar', sv: 'Kassaflödeskalender', formula: 'coupon = nominal × coupon % / f on each schedule date;  redemption = nominal at maturity\nswap = ±N × (fixed − par) / f per period (estimate);  CDS premium = ±N × spread / 4 on IMM dates (20 Mar/Jun/Sep/Dec)\nFX forward = both legs at maturity;  option/future expiry = informational (intrinsic value / notional), not cash', notes: { en: 'Projected cash = cash today + cumulative net cash events per month.', sv: 'Prognostiserad kassa = kassa i dag + ackumulerade nettokassahändelser per månad.' } },
      { en: 'UCITS SRRI', sv: 'UCITS SRRI', formula: 'σ_w = stdev(weekly returns, last 5 years) · √52\nclass 1: < 0.5 %, 2: 0.5–2 %, 3: 2–5 %, 4: 5–10 %, 5: 10–15 %, 6: 15–25 %, 7: ≥ 25 %', notes: { en: 'CESR/10-673. Weekly = last observation of each ISO week. Flagged as incomplete with less than five years of data.', sv: 'CESR/10-673. Vecka = sista observationen i varje ISO-vecka. Flaggas som ofullständig vid mindre än fem års data.' } },
      { en: 'PRIIPs SRI (category 2)', sv: 'PRIIPs SRI (kategori 2)', formula: 'daily log returns r, N = 256 × RHP years, μ1 = skew, μ2 = excess kurtosis\nVaR_ret = σ√N (−1.96 + 0.474 μ1/√N − 0.0687 μ2/N + 0.146 μ1²/N) − ½σ²N   (Cornish-Fisher, 97.5 %)\nVEV = (√(3.842 − 2 VaR_ret) − 1.96) / √RHP\nMRM from VEV: 1: < 0.5 %, 2: 0.5–5 %, 3: 5–12 %, 4: 12–20 %, 5: 20–30 %, 6: 30–80 %, 7: ≥ 80 %;  SRI = table(MRM, CRM)', notes: { en: 'Commission Delegated Regulation (EU) 2017/653, Annex II (MRM) and Annex III (SRI table). The credit risk measure (CRM) is entered, not computed.', sv: 'Kommissionens delegerade förordning (EU) 2017/653, bilaga II (MRM) och bilaga III (SRI-tabell). Kreditriskmåttet (CRM) anges, beräknas inte.' }, params: 'rhp (years), crm, sriSource' },
      { en: 'Indicative NAV per unit', sv: 'Indikativt NAV per andel', formula: 'net assets = Σ MV − liabilities + receivables\nclass share = units × last NAV × FX / Σ over classes;  accrued fee = fee % × class assets × days / 365\nNAV per unit = (class assets − accrued fee) / FX_class / units', notes: { en: 'Fees accrue linearly on actual/365 from the entered start date. The flow simulator adds or removes base-currency cash and re-runs liquidity and the investment rules; it does not decide which assets to sell.', sv: 'Avgiften läggs upp linjärt på faktiska dagar/365 från angivet startdatum. Flödessimulatorn lägger till eller drar ifrån kassa i basvaluta och kör om likviditet och placeringsregler; den väljer inte vilka tillgångar som säljs.' } }
    ]
  },
  {
    id: 'data', module: 'store.js · importer.js · filelink.js',
    title: { en: 'Data, sources and storage', sv: 'Data, källor och lagring' },
    items: [
      { en: 'Prices and reported figures', sv: 'Kurser och rapporterade värden', formula: 'entered by hand or imported from your files (CSV, TSV, Excel, JSON, XML)', notes: { en: 'Nothing is fetched from brokers, custodians or market-data vendors. Reported notional and delta come from the same files.', sv: 'Ingenting hämtas från mäklare, förvaringsinstitut eller marknadsdataleverantörer. Rapporterat nominellt värde och delta kommer från samma filer.' } },
      { en: 'FX rates', sv: 'Valutakurser', formula: 'stored as EUR crosses;  base per CCY = EUR/base ÷ EUR/CCY', notes: { en: 'ECB reference rates read from the ECB\'s own file (eurofxref CSV or XML, downloaded by you), a built-in fallback table, or your own rates in Settings. Historical FX for the back-cast comes from series named CCY+BASE in the price history.', sv: 'ECB:s referenskurser inlästa från ECB:s egen fil (eurofxref CSV eller XML, som du laddar ner), en inbyggd reservtabell eller egna kurser i Inställningar. Historisk valuta för back-cast kommer från serier med namnet CCY+BAS i kurshistoriken.' } },
      { en: 'Storage', sv: 'Lagring', formula: 'browser localStorage (this device only) + optional linked file on your computer + backup files', notes: { en: 'Nothing is sent to a server. Charts, PDF and Excel libraries are loaded from a CDN with integrity hashes (SheetJS excepted, see README).', sv: 'Ingenting skickas till någon server. Bibliotek för diagram, PDF och Excel laddas från CDN med integritetshashar (SheetJS undantaget, se README).' } }
    ]
  }
];
