// Golden figures (tests/golden/figures.mjs) against the frozen fixture.
//   node scripts/golden.mjs                 compare and print; exits 1 if anything changed
//   node scripts/golden.mjs --update        accept the current figures as the new fixture
//   node scripts/golden.mjs --report out.md write a Markdown validation report (used by the release)
import { readFileSync, writeFileSync } from 'node:fs';
import { computeFigures, compare, VAL_DATE, REL_TOL, INDEPENDENT } from '../tests/golden/figures.mjs';

const FIXTURE = new URL('../tests/fixtures/golden-expected.json', import.meta.url);
const args = process.argv.slice(2);
const figures = computeFigures();

if (args.includes('--update')) {
  const out = { valDate: VAL_DATE, note: 'Generated by scripts/golden.mjs --update. Do not edit by hand.', figures: figures.map(([key, value, what]) => ({ key, value, what })) };
  writeFileSync(FIXTURE, JSON.stringify(out, null, 2) + '\n');
  console.log(`wrote ${figures.length} figures`);
  process.exit(0);
}

const expected = JSON.parse(readFileSync(FIXTURE, 'utf8'));
const rows = compare(figures, expected.figures);
const changed = rows.filter(r => r.status !== 'ok');
const fmt = x => (x === null || x === undefined ? '—' : Number.isInteger(x) ? String(x) : x.toPrecision(10));

const ri = args.indexOf('--report');
if (ri >= 0) {
  const indep = Object.entries(INDEPENDENT).map(([k, [want, tol]]) => {
    const got = figures.find(f => f[0] === k)[1];
    return `| \`${k}\` | ${fmt(got)} | ${fmt(want)} ± ${tol} | ${Math.abs(got - want) <= tol ? 'pass' : '**FAIL**'} |`;
  });
  const md = [
    '# Calculation validation report',
    '',
    `Version: ${process.env.GITHUB_REF_NAME || 'local'} · commit ${process.env.GITHUB_SHA || 'n/a'} · Node ${process.version}`,
    '',
    `Demo fund (seeded, synthetic prices) valued at ${VAL_DATE}. Each figure is compared with the value frozen in`,
    '`tests/fixtures/golden-expected.json` (relative tolerance ' + REL_TOL + '). A frozen value is what the code computed when',
    'it was last accepted: this proves the numbers did not move, not that they are right. The closed-form section is independent.',
    '',
    `**Result: ${changed.length ? `${changed.length} figure(s) differ` : `all ${rows.length} figures unchanged`}.**`,
    '',
    '## Closed-form checks',
    '',
    '| Figure | Computed | Expected | Result |', '|---|---:|---:|---|', ...indep,
    '',
    '## Frozen figures',
    '',
    '| Figure | Description | Computed | Frozen | Result |', '|---|---|---:|---:|---|',
    ...rows.map(r => `| \`${r.key}\` | ${r.what} | ${fmt(r.actual)} | ${fmt(r.expected)} | ${r.status === 'ok' ? 'ok' : `**${r.status}**`} |`),
    ''
  ].join('\n');
  writeFileSync(args[ri + 1], md);
  console.log(`wrote ${args[ri + 1]}`);
}

if (changed.length) {
  for (const r of changed) console.log(`${r.status.padEnd(8)}${r.key}: expected ${fmt(r.expected)}, got ${fmt(r.actual)}`);
  process.exit(1);
}
console.log(`all ${rows.length} golden figures unchanged`);
